"""
Part 1: Content definitions for Chapters 1-2 (expanded to hit 50-55 pages).
"""

# ── Chapter 1 expansions ──────────────────────────────────────────────

CH1_INTRO_EXTRA = """The healthcare landscape in developing countries is marked by a severe imbalance between the demand for specialist medical services and the available supply of qualified practitioners. According to the World Health Organization, approximately half of the global population lacks access to essential health services, with the deficit being most acute in rural and semi-urban regions. In such environments, patients frequently rely on informal consultations, unverified internet resources, or delayed referrals to distant hospitals, all of which contribute to misdiagnosis, treatment delays, and preventable morbidity.

Artificial intelligence, and in particular large language models combined with retrieval-augmented generation, offers a transformative opportunity to bridge this gap. By grounding language model outputs in curated medical knowledge bases, RAG systems can provide evidence-based clinical guidance without the hallucination risks inherent in purely generative approaches. However, the vast majority of existing medical AI systems treat every patient identically, ignoring the clinically critical differences in allergies, current medications, blood type, and recent vital signs that should fundamentally shape any medical recommendation.

MediBOT addresses this shortcoming through a patient-context injection mechanism that serializes the individual's clinical profile into the generation prompt before retrieval and response synthesis. This ensures that every response is not only medically grounded but also personalized to the specific patient's clinical situation. The system further extends its utility by integrating a convolutional neural network for chest X-ray classification and an optical character recognition pipeline for digitizing paper-based medical reports, all within an offline-capable Progressive Web Application architecture.

The platform is architected as a three-tier system comprising a React-based frontend with IndexedDB persistence via Dexie.js, a FastAPI middleware layer responsible for request validation, rate limiting, and cross-origin resource sharing, and a machine learning backend that orchestrates Llama-2 7B inference, FAISS vector retrieval, ResNet101 image classification, and EasyOCR text extraction. This layered design ensures separation of concerns, independent scalability of each tier, and the ability to swap individual components such as the language model or the embedding strategy without disrupting the overall system."""

CH1_PROBLEM_EXTRA = """The problem is further compounded by the fragmentation of clinical workflows across disconnected systems. A typical patient in a resource-limited setting may have paper-based prescriptions from one clinic, handwritten lab reports from another, and no centralized digital record linking these documents. When such a patient seeks AI-powered medical guidance, existing systems have no mechanism to incorporate this fragmented history into their reasoning process.

Additionally, the reliance on cloud-based inference for medical AI creates a fundamental accessibility paradox: the populations that stand to benefit most from AI-powered clinical guidance are precisely those with the least reliable internet connectivity. A system that becomes non-functional during network outages provides no value in the very scenarios where it is most needed. This necessitates an offline-first architectural approach where critical data and functionality remain available regardless of connectivity status.

The challenge of medical image interpretation in underserved areas is equally pressing. While chest radiography is one of the most cost-effective screening modalities for pulmonary diseases, the interpretation of X-ray images requires specialized radiological expertise that is scarce in rural settings. An automated classification system that can provide preliminary screening results with confidence scores and severity assessments can serve as a valuable decision support tool for frontline healthcare workers who lack access to specialist radiologists."""

CH1_MOTIVATION_EXTRA = """Furthermore, the global COVID-19 pandemic has underscored the urgent need for accessible diagnostic tools that can operate at scale without requiring physical visits to overcrowded healthcare facilities. The pandemic demonstrated that AI-powered screening tools for respiratory conditions can significantly reduce the burden on healthcare systems by triaging patients who require immediate attention from those who can be monitored remotely.

The convergence of several technological advances makes this project particularly timely. Transfer learning has reduced the data requirements for training accurate medical image classifiers; quantized language models can now run on consumer-grade hardware; vector similarity search enables efficient retrieval from large medical knowledge bases; and Progressive Web Application standards provide a robust framework for offline-capable web applications. MediBOT leverages all of these advances to create a system that would have been impractical even two years ago.

From an ethical standpoint, the project is motivated by the principle that access to reliable medical guidance should not be contingent on geographic location or economic status. By designing a system that works offline, personalizes its responses to individual clinical profiles, and provides transparent source citations for its recommendations, MediBOT aims to democratize access to clinical intelligence while maintaining the safety standards expected of healthcare technology."""

CH1_SDG_EXTRA = """Specifically, the project addresses SDG Target 3.8, which focuses on achieving universal health coverage, including access to quality essential healthcare services and access to safe, effective, quality, and affordable essential medicines. By providing AI-powered diagnostic screening and personalized medical guidance through an offline-capable platform, MediBOT extends the reach of quality healthcare services to populations that are currently underserved.

The project also contributes to SDG Target 3.d, which calls for strengthening the capacity of all countries for early warning, risk reduction, and management of national and global health risks. The chest X-ray classification system enables early detection of conditions such as tuberculosis and pneumonia, which remain leading causes of mortality in developing countries. Early detection through automated screening can significantly improve treatment outcomes and reduce the spread of communicable diseases.

Additionally, the offline-first design philosophy aligns with SDG Target 9.c, which advocates for significantly increasing access to information and communications technology. By ensuring that the platform functions without continuous internet connectivity, MediBOT removes a critical barrier to technology adoption in regions where network infrastructure remains underdeveloped."""


# ── Chapter 2 expansions ──────────────────────────────────────────────

CH2_OVERVIEW_EXTRA = """The convergence of natural language processing, computer vision, and clinical informatics has created a fertile landscape for AI-driven healthcare applications. Language models such as GPT-4, Llama-2, and Gemini have demonstrated remarkable capabilities in understanding and generating medical text, yet their deployment in clinical settings requires careful consideration of grounding, personalization, and safety.

Retrieval-Augmented Generation represents a paradigm shift in how language models access and utilize domain knowledge. Unlike fine-tuning, which permanently encodes knowledge into model parameters, RAG dynamically retrieves relevant documents at inference time, ensuring that responses are grounded in verifiable sources. This is particularly valuable in healthcare, where medical knowledge evolves rapidly and the ability to trace recommendations back to authoritative sources is a fundamental requirement for clinical trust.

The embedding models used for retrieval, such as sentence-transformers and MiniLM variants, convert medical text into dense vector representations that capture semantic similarity. Facebook AI Similarity Search provides efficient nearest-neighbor lookup in these vector spaces, enabling sub-millisecond retrieval even from knowledge bases containing millions of document chunks. The combination of dense retrieval with generative language models creates a system that is both knowledgeable and articulate, capable of synthesizing information from multiple sources into coherent clinical guidance.

In the domain of medical imaging, deep learning has revolutionized automated diagnosis. Convolutional neural networks, particularly those based on residual architectures such as ResNet, have achieved expert-level performance on tasks including chest X-ray classification. The key insight behind transfer learning is that low-level visual features learned on large-scale datasets like ImageNet transfer effectively to medical imaging tasks, dramatically reducing the amount of labeled medical data required for training.

Optical character recognition has evolved from simple template-matching approaches to sophisticated deep learning pipelines. EasyOCR, built on CRAFT text detection and recognition networks, provides a practical solution for extracting text from photographed medical documents. When combined with zero-shot extraction capabilities of large language models, OCR becomes a powerful tool for converting unstructured medical documents into structured clinical data."""

CH2_MODELS_EXTRA = """Each of these existing models and frameworks represents a significant contribution to the field, yet none provides the comprehensive, personalized, and offline-capable clinical intelligence that MediBOT aims to deliver. Generic medical chatbots operate on the principle of broad generalization, drawing from vast training corpora that include medical literature, clinical guidelines, and patient forums. While these systems can provide useful general medical information, they fundamentally lack the ability to contextualize their responses based on individual patient data. A patient with a known allergy to NSAIDs receiving a recommendation for ibuprofen represents a critical safety failure that arises from the absence of patient-context awareness.

Med-PaLM and its successor Med-PaLM 2 represent the state of the art in medical question answering, achieving expert-level performance on USMLE-style medical examinations. However, these systems are proprietary, require significant computational resources, and do not provide mechanisms for patient-specific context injection. Their cloud-only deployment model also makes them unsuitable for environments with unreliable connectivity.

CheXNet demonstrated that deep learning can achieve radiologist-level accuracy in detecting pneumonia from chest X-rays. However, the original CheXNet model was limited to binary classification and did not integrate with broader clinical decision support workflows. MediBOT extends this concept by implementing five-class classification using ResNet101, providing severity assessments, and connecting diagnostic results to the patient's overall clinical profile."""

CH2_LIMITATIONS_EXTRA = """These limitations collectively define the research gap that MediBOT addresses. The absence of patient-context awareness in existing systems is not merely a feature gap but a safety concern. In clinical practice, the same medical question can have fundamentally different correct answers depending on the patient's specific circumstances. A recommendation for aspirin may be appropriate for one patient but dangerous for another who is already taking anticoagulants.

The cloud dependency of existing systems creates an inequitable distribution of AI-powered healthcare, where the benefits accrue primarily to populations with reliable high-speed internet access. This digital divide mirrors and reinforces existing healthcare disparities, making it imperative that new systems adopt architectures that degrade gracefully under poor connectivity conditions.

The siloed nature of existing medical AI tools forces healthcare workers to navigate between multiple disconnected applications for different clinical tasks. A system that unifies text-based reasoning, image analysis, and document processing within a single platform reduces cognitive load, minimizes context switching, and enables cross-modal insights that are impossible when these capabilities exist in isolation."""

CH2_OBJECTIVES_EXTRA = """These research objectives are designed to address the identified limitations systematically while maintaining a focus on practical deployability. Each objective corresponds to a specific technical contribution that, when combined, creates a system greater than the sum of its parts.

The patient-context injection mechanism goes beyond simple prompt engineering by implementing a structured serialization protocol that consistently represents patient demographics, allergies, medications, and vital signs in a format that the language model can reliably parse and utilize. This structured approach ensures that context is not lost or misinterpreted during the generation process.

The offline-first design leverages IndexedDB through the Dexie.js wrapper to maintain a complete local copy of the patient's clinical data, chat history, and diagnostic results. A delta-sync mechanism ensures that locally created records are eventually propagated to the cloud database when connectivity returns, preventing data loss and maintaining consistency across sessions."""

CH2_BACKLOG_EXTRA = """This figure illustrates the complete product backlog organized by sprint and priority level. Each user story is mapped to specific acceptance criteria and linked to the corresponding system components that implement the required functionality. The backlog was prioritized using the MoSCoW framework, categorizing features as Must-have, Should-have, Could-have, and Won't-have for the current release cycle. Must-have items include the personalized RAG pipeline, chest X-ray classification, offline data persistence, and role-based authentication."""

CH2_PLAN_EXTRA = """This figure shows the project roadmap with key milestones, dependencies, and deliverables for each development phase. Sprint I establishes the core platform infrastructure including authentication, the patient dashboard, and the personalized RAG pipeline. Sprint II extends the platform with medical imaging capabilities, OCR-based report extraction, and the doctor dashboard. This phased approach allows for early validation of the core architecture before building more complex features on top of it."""
